# Generated by Django 3.2.22 on 2023-11-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_terminon', models.DateTimeField()),
                ('titulo', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=700)),
                ('tipo', models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('SA', 'Suspencion de Actividades'), ('SAP', 'Suspencion de Actividades PM'), ('P', 'Periodo Lectivo'), ('SE', 'Suspension de Evaluaciones'), ('C', 'Ceremonia'), ('ED', 'EDDA'), ('E', 'Evaluacion'), ('A', 'Ayudantias'), ('H', 'Hito Academico'), ('S', 'Secretaria Academica'), ('O', 'OAI')], default='S', max_length=20)),
                ('segmento', models.ManyToManyField(to='core.Segmento')),
            ],
        ),
    ]
