# Generated by Django 3.2.22 on 2023-11-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_terminon',
            new_name='fecha_termino',
        ),
    ]
