# Generated by Django 4.2.6 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fecha_terminon_evento_fecha_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='segmento',
        ),
        migrations.DeleteModel(
            name='Segmento',
        ),
        migrations.AddField(
            model_name='evento',
            name='segmento',
            field=models.CharField(choices=[('C', 'Comunidad USM'), ('E', 'Estudiante'), ('P', 'Profesor'), ('J', 'Jefe de Carrerra')], default='C', max_length=20),
        ),
    ]
